import random



def in_or_out():
    print("\t\t\t\t\t---------------------------------------\n")
    print("\t\t\t\t\t|             IN OR OUT!!             |\n")
    print("\t\t\t\t\t---------------------------------------\n\n")
    print("Machine will generate 3 numbers and u will be shown 2 numbers")
    print("You should guess w+hether the 3rd number guessed by machine is in the middle or not")
    print("-------------------------------------------------------------------------\n")
    print("| NOTE : ALL 3 NUMBERS GENERATED BY THE MACHINE ARE IN THE RANGE 0 - 40.|\n")
    print("-------------------------------------------------------------------------\n")
    num_1 = random.randrange(0, 40)
    num_2 = random.randrange(0, 40)
    num_3 = random.randrange(0, 40)
    while (num_1 == num_2 or num_1 == num_2+1):
        if (num_1 == num_1+1 or num_1 == num_1+2 or num_1 == num_1):
            num_2 = random.randrange(1, 40)
    if (num_1 > num_2):
        temp = num_1
        num_1 = num_2
        num_2 = temp
    print('Number 1 is : ' + str(num_1))
    print('Number 2 is : ' + str(num_2))
    print("If you think the 3rd number is in the middle press 'Y'")
    print("If you think the 3rd number is not in the middle press 'N'")
    choice = input()
    if (choice == 'Y' or choice == 'y') and (num_1 < num_3 and num_2 > num_3):
        print('Yes!!! Your guess is right')
    elif (choice == 'N' or choice == 'n') and ((num_1 > num_3 and num_2 > num_3) or (num_1 < num_3 and num_2 < num_3)):
        print('Yes!!! Your guess is right')
    else:
        print("No! You are wrong")
    print('Number 3 is : '+str(num_3))



def guess_what():
    print("\t\t\t\t\t---------------------------------------\n")
    print("\t\t\t\t\t|            Guess What!!!            |\n")
    print("\t\t\t\t\t---------------------------------------\n\n")
    print("There are 2 randomly generated numbers which wont be shown \nJust guess a number in between the numbers guessed by machine using the given hint")
    print("\n\t\t\tALL THE BEST!!!\n")
    num_1 = random.randrange(1, 40)
    num_2 = random.randrange(1, 40)
    while (num_1 == num_2 or num_1 == num_2+1):
        if (num_1 == num_1+1 or num_1 == num_1+2 or num_1 == num_1):
            num_2 = random.randrange(1, 40)
    if (num_1 > num_2):
        temp = num_1
        num_1 = num_2
        num_2 = temp
    print("Hint : There are " + str(num_2 - num_1) +
          " numbers in between number 1 and number 2\n")
    print("-------------------------------------------------------------------------\n")
    print("| NOTE: BOTH 2 NUMBERS GENERATED BY THE MACHINE ARE IN THE RANGE 0 - 40.|\n")
    print("-------------------------------------------------------------------------\n")
    print("TO EXIT THE LOOP PRESS A NUMBER GREATER THAN 40")
    print("Enter a number between 0 and 40 : ", end=" ")
    guess = int(input())
    while (num_1 > guess and num_2 > guess) or (num_1 < guess and num_2 < guess):
        print("TRY AGAIN")
        guess = int(input())
        if (guess > 40):
            break
    if num_1 < guess and num_2 > guess:
        print("YOU WON!")
    else:
        print("YOU LOST!\nBetter luck next time")

    print("The Numbers are\nNumber 1: "+str(num_1)+"\nNumber 2: " + str(num_2))



def hi_lo_game():
    print("\t\t\t\t\t---------------------------------------\n")
    print("\t\t\t\t\t|       Welcome to Hi-Lo game         |\n")
    print("\t\t\t\t\t---------------------------------------\n\n")
    n = random.randrange(1, 100)
    count = 0
    guess = int(input("Enter any number in the range 100: "))
    while n != guess and count != 10:
        if guess < n:
            print("Think of a big number!")
            count = count + 1
            guess = int(input("Enter number again: "))
        elif guess > n:
            print("Think of a small number!")
            count = count + 1
            guess = int(input("Enter number again: "))
        else:
            break
    if (count != 10 and guess == n):
        print("You guessed it right!!")
    else:
        print("Chances exceeded")



def initialize():
    print("\t\t\t---------------------------------------------------------------------------------------------------------------------------------------------------------------\n"
          "\t\t\t |||||||||||||| |||||||||||||| ||||||          |||||| ||||||||||||||    ||||||          |||||| |||||||||||||| ||||||||||||||||   ||||||         ||||||||||||   \n"
          "\t\t\t |||||||||||||| |||||||||||||| |||||||||||||||||||||| ||||||||||||||    ||||||          |||||| |||||||||||||| ||||||||||||||||   ||||||         |||||||||||||| \n"
          "\t\t\t |||||||||||||| |||||||||||||| |||||||||||||||||||||| ||||||||||||||    ||||||          |||||| |||||||||||||| ||||||||||||||||   ||||||         |||||||||||||| \n"
          "\t\t\t ||||||         ||||||  |||||| |||||||||||||||||||||| ||||||            ||||||          |||||| ||||||  |||||| ||||||    ||||||   ||||||         ||||||  |||||| \n"
          "\t\t\t ||||||         |||||||||||||| ||||||  ||||||  |||||| ||||||||||||||    ||||||  ||||||  |||||| ||||||  |||||| ||||||||||||||||   ||||||         ||||||  |||||| \n"
          "\t\t\t ||||||  |||||| |||||||||||||| ||||||  ||||||  |||||| ||||||||||||||    ||||||  ||||||  |||||| ||||||  |||||| ||||||||||||||||   ||||||         ||||||  |||||| \n"
          "\t\t\t ||||||  |||||| |||||||||||||| ||||||  ||||||  |||||| ||||||||||||||    ||||||  ||||||  |||||| ||||||  |||||| ||||||||||||||||   ||||||         ||||||  |||||| \n"
          "\t\t\t ||||||  |||||| ||||||  |||||| ||||||          |||||| ||||||            |||||||||||||||||||||| ||||||  |||||| ||||||  ||||||     ||||||         ||||||  |||||| \n"
          "\t\t\t |||||||||||||| ||||||  |||||| ||||||          |||||| ||||||||||||||    |||||||||||||||||||||| |||||||||||||| ||||||  |||||||||| |||||||||||||| |||||||||||||| \n"
          "\t\t\t |||||||||||||| ||||||  |||||| ||||||          |||||| ||||||||||||||    |||||||||||||||||||||| |||||||||||||| ||||||  |||||||||| |||||||||||||| |||||||||||||| \n"
          "\t\t\t |||||||||||||| ||||||  |||||| ||||||          |||||| ||||||||||||||    ||||||  ||||||  |||||| |||||||||||||| ||||||  |||||||||| |||||||||||||| ||||||||||||   \n"
          "\t\t\t------------------------------------------------------------------------------------------------------------------------------------------------------------\n")



if __name__ == "__main__":
    n = 0
    print("Welcome!!!")
    initialize()
    print("Your ID is: " + str(random.randrange(50000, 999999)))
    print("Here we have 3 amazing number guessing games !!\n\nGO Ahead !!! Choose 1 of 3")
    while n != 4:
        print("\n\tEnter 1 for Hi-Lo Game\n")
        print("\tEnter 2 for Guess What ! game\n")
        print("\tEnter 3 for In or Out !! game\n")
        print("\tEnter 4 to Exit\n")
        print("Enter:", end=' ')
        n = int(input())
        if n == 1:
            hi_lo_game()
        elif n == 2:
            guess_what()
        elif n == 3:
            in_or_out()
        else:
            print("HAVE A GREAT DAY")
            exit
